import InnerPage from '@/components/InnerPage';
import pages from '@/data/pages.json';
import type { Metadata } from 'next';
import { SchemaScripts, profilePage, breadcrumb, faqPage, audioObject, videoObject } from '@/lib/staticPageSchema';

const data = (pages as Record<string, Record<string, string>>)['seo18'];

export const metadata: Metadata = {
  alternates: {
    canonical: `https://www.voiceoverguy.co.uk/david-attenborough-voice`,
  },
  title: data.s1,
  description: data.s2,
};

const schemas = [
  profilePage('david-attenborough-voice', 'Guy Harris is an award-winning British male voiceover artist, known for his David Attenborough impression voiceovers used in TV, games, social campaigns and promos.'),
  breadcrumb('david-attenborough-voice', 'David Attenborough Voice'),
  audioObject('david-attenborough-voice', 'David Attenborough Voiceover Demo \u2013 Guy Harris', 'A natural David Attenborough-style narration performed by British male voiceover artist Guy Harris.', '/assets/audio/david-attenborough-demo-25-guy-harris.mp3', 'PT1M26S'),
  videoObject('david-attenborough-voice', 'David Attenborough Voice Demo \u2013 Main Video', 'Cracking Ice \u2013 A nature-style narration over skaters enjoying King Winter\u2019s reign in the Netherlands, voiced in a David Attenborough impression by Guy Harris.', 't0DqlSVh6hc'),
  faqPage('david-attenborough-voice', [
    { q: 'Who is the most famous wildlife narrator?', a: 'Sir David Attenborough is widely regarded as the most famous wildlife narrator, with a career spanning decades of natural history documentaries.' },
    { q: "Is David Attenborough's voice AI?", a: 'While AI voice generators exist, Guy Harris provides a natural David Attenborough impression voiceover, delivering nuance and storytelling that AI cannot replicate.' },
    { q: 'Is this Attenborough voice generated by AI?', a: 'No. This is a real voiceover performed by award-winning British voice artist Guy Harris, using his own voice to create a natural, respectful Attenborough-style narration.' },
    { q: 'Who has 32 honorary degrees?', a: 'Sir David Attenborough has been awarded 32 honorary degrees from universities worldwide, recognising his influence on broadcasting and education.' },
  ]),
];

export default function Page() {
  return (
    <main className="inner-page">
      {data.s3 && (
        <section className="inner-hero">
          <div className="inner-container" dangerouslySetInnerHTML={{ __html: data.s3 }} />
        </section>
      )}
      <div className="inner-bar" />
      <InnerPage pageTitle={data.s1} pageSlug="david-attenborough-voice" sections={[
        ...(data.s4 ? [{ text: data.s4 }] : []),
        ...(data.s7 ? [{ youtubeId: data.s7 }] : []),
        ...(data.s5 ? [{ text: data.s5 }] : []),
        ...(data.s8 ? [{ youtubeId: data.s8 }] : []),
        ...(data.s6 ? [{ text: data.s6 }] : []),
        { imageSrc: '/assets/images/attenborough-script-generator.jpg', imageAlt: 'David Attenborough Impression \u2013 Guy Harris' },
      ]} />
      <SchemaScripts schemas={schemas} />
    </main>
  );
}
